### ISSUE TITLE
Theft and Custody

### ISSUE THREAD

**Issue by workergnome** [gri-is/crom#11]
Re-flagging this as something potentially worth talking about—Art Tracks has modeled both theft and loss as ownership transfers, not as merely custody transfers—If a work is documented as stolen/and or lost, there is no functional ownership.

(This would invalidate and/or reopen issue #10.)  

Not a deal-breaker, and we'd be willing to modify our model to accommodate—better to have a consistent concept across the two.

**Comment by azaroth42** [comment]
Propose to move modeling discussion to azaroth42/museum-lod and keep this set for just library issues?

**Comment by workergnome** [comment]
👍🏼
