### ISSUE TITLE
Remove context auto-typing from literal ranges

### ISSUE THREAD

**Issue by azaroth42** [gri-is/crom#6]
As it breaks framing from triples if the data type is not present ... which it likely will not be.

For example, if the type is explicitly set in the context to be xsd:dateTime, and the incoming RDF triples do not assert the type of the literal, then it will assume it's NOT a dateTime and hence not something to be recorded in the JSON-LD serialization as it doesn't fit the context of the frame.

The reason these were in the context is that the other direction makes it nice -- it automatically asserts the datatype when going from JSON-LD to triples.  For CRM (compared to IIIF for example) there is likely to be a lot of data managed as triples, so this is a relatively significant impediment, and one that would be easily missed.

(Thanks again to @workergnome)

**Comment by azaroth42** [comment]
Clarifying -- we should also remove the `xsd:dateTime` types, not just the `xsd:string` etc?

**Comment by workergnome** [comment]
Yes.  Though perhaps we should, at a later date, consider two profiles, a strict one with types (for validation) and a loose one?

**Comment by azaroth42** [comment]
Done. And yes, validation is important -- but not necessarily the same technology as the context.
Thinking json-schema, shex/shacl, etc.
